#!/usr/bin/env python3
"""Project the claims onto one directory per address: places/<subject_id>/PLACE.yml.

Mechanical, idempotent, and it NEVER overwrites an existing file. Hand-authored records
(the 420 Café and its neighbours) are richer than anything a generator can write, so they
win; this only fills in the addresses nobody has written yet.

WHAT GOES IN, and why the list is short:
  gedooglijst        official, public, the authority on whether an address is tolerated
  photos-2009        Don's own camera and GPS — the only coordinates published here
  placesdata-2011    Don's own field notes: names, phone, website. NOT its coordinates.
  from-comments-2013 facts we extracted in our own words

WHAT STAYS OUT:
  claims-cannamaps.csv — somebody else's compilation. Local only, per .gitignore.
  placesdata-2011 coordinates — geocoded beside Google Place pages. One marked example in a
    hand-written file is a fact; 228 of them is bulk extraction from a Google-derived
    compilation, which is the same reason data/register.csv is gitignored. They stay in
    data/claims-2009.csv on the machine that made them.

Usage: python3 scripts/build_places.py [--force-empty]
       --force-empty rewrites generated files that have no hand edits (mtime check is not
       used; the header line is the marker).
"""

import csv
import json
import os
import sys
from collections import defaultdict

import yaml

sys.path.insert(0, os.path.dirname(__file__))
from addr import dutch_title, split_number, subject_id  # noqa: E402

ROSTER = "data/gedooglijst-2026-03-05.csv"
CLAIMS = "data/claims-2009.csv"
COMMENTS = "data/from-comments-2013.yml"
PLACES = "places"
MARKER = "# GENERATED by scripts/build_places.py"


def load_roster():
    out = {}
    for r in csv.DictReader(open(ROSTER)):
        num, tail = split_number(r["number"])
        out[subject_id(r["street_raw"], num, "")] = {
            "street": dutch_title(r["street_raw"]),
            "number": num,
            "suffix": r["suffix"] or tail or "",
            "postcode": r["postcode"],
            "valid_from": r["valid_from"],
            "source_url": r["source_url"],
        }
    return out


def load_claims():
    by_subject = defaultdict(lambda: defaultdict(list))
    for c in csv.DictReader(open(CLAIMS)):
        by_subject[c["subject"]][c["field"]].append(c)
    return by_subject


def load_comments():
    d = yaml.safe_load(open(COMMENTS))
    return {k: v for k, v in d.items()
            if isinstance(v, dict) and k not in ("patterns_across_the_corpus",)}


def q(v):
    """Quote a value for YAML. JSON is a YAML subset, and unlike yaml.dump() for a bare
    scalar it does not append a `...` document-end marker into the middle of the file."""
    return json.dumps(v, ensure_ascii=False)


def first(claims, field):
    return claims.get(field, [{}])[0].get("value") or None


def own_coordinate(claims):
    """photos-2009 only. Don's camera, Don's GPS, the only OSM-eligible fix we hold."""
    for c in claims.get("coordinate", []):
        if c["source"] == "photos-2009":
            return c
    return None


def emit(sid, roster, claims, comments):
    lines = [MARKER, "# Hand-edit freely: delete this header and the generator leaves it alone.", ""]
    tolerated = sid in roster
    r = roster.get(sid, {})

    lines.append("inherits: [coffeeshop, room, place]")
    lines.append("")
    lines.append(f"id: {sid}")
    lines.append("")

    # Address. The roster is the authority when it has the row; otherwise reconstruct from
    # the id, which is lossy about the street's real spelling and says so.
    lines.append("address:")
    if tolerated:
        lines.append(f"  street: {r['street']}")
        lines.append(f"  number: {r['number']}")
        if r["suffix"]:
            lines.append(f"  suffix: {r['suffix']}          # roster huisletter; the door may disagree")
        lines.append(f"  postcode: {r['postcode']}")
    else:
        street, _, num = sid.rpartition("-")
        lines.append(f"  street: {dutch_title(street.replace('-', ' '))}   # reconstructed from the id")
        lines.append(f"  number: {num}")
        lines.append("  postcode: unknown")
    lines.append("  city: Amsterdam")
    lines.append("  country: NL")
    lines.append("  tz: Europe/Amsterdam")
    lines.append("")

    lines.append("gedoog:")
    if tolerated:
        lines.append("  tolerated: true")
        lines.append("  roster: gedooglijst-2026-03-05")
        lines.append(f"  valid_from: {r['valid_from']}")
        lines.append(f"  source: \"{r['source_url']}\"")
    else:
        lines.append("  tolerated: false")
        lines.append("  roster: gedooglijst-2026-03-05")
        lines.append("  # Not on the 2026 roster. Could be closed, could be renumbered, could be")
        lines.append("  # a bad address in the old data. Absence from a roster is not a closure.")
        lines.append("  status: off-roster")
    lines.append("")

    coord = own_coordinate(claims)
    lines.append("coordinates:")
    if coord:
        heading = first(claims, "photo_heading")
        lines.append("  claims:")
        lines.append(f"    - lat: {coord['value'].split(',')[0]}")
        lines.append(f"      lng: {coord['value'].split(',')[1]}")
        lines.append("      source: photos-2009")
        lines.append(f"      observed: {coord['observed']}")
        if heading:
            lines.append(f"      heading: {heading}          # camera bearing, degrees true")
    else:
        lines.append("  claims: []          # no own fix. A 2011 geocode exists locally; not published.")
    lines.append("")

    name = first(claims, "name")
    aka = first(claims, "also_known_as")
    sort_name = first(claims, "sort_name")
    if name:
        lines.append("names:")
        lines.append(f"  current: {q(name)}          # 2011 sheet, unverified since")
        if aka:
            lines.append(f"  also_known_as: [{q(aka)}]")
        if sort_name:
            lines.append(f"  sort_name: {q(sort_name)}")
        lines.append("")

    phone, website = first(claims, "phone"), first(claims, "website")
    if phone or website:
        lines.append("contact:")
        if phone:
            lines.append(f"  phone: \"{phone}\"          # 2011, verify before dialling")
        if website:
            lines.append(f"  website: \"{website}\"")
        lines.append("")

    photo = first(claims, "key_photo")
    if photo:
        lines.append("survey:")
        lines.append("  - visited: 2009-10-04")
        lines.append("    by: don")
        lines.append(f"    key_photo: {photo}          # in the old Coffeeshops trunk, not vendored")
        lines.append("")

    if sid in comments:
        lines.append("from_visitor_comments:")
        lines.append("  # Facts from 2013 site comments, our words, commenters unnamed.")
        for k, v in comments[sid].items():
            lines.append(f"  {k}: {q(v)}")
        lines.append("")

    reasons = []
    if not coord:
        reasons.append("no-coordinate")
    if not name:
        reasons.append("no-name")
    if tolerated and not photo:
        reasons.append("never-photographed")
    if not tolerated:
        reasons.append("off-roster-unexplained")
    if tolerated and r["suffix"]:
        reasons.append("huisletter-unverified")
    reasons.append("stale-everything" if photo else "no-evidence-since-2011")
    lines.append("review:")
    lines.append(f"  priority: {'high' if not tolerated or not coord else 'medium'}")
    lines.append(f"  reasons: [{', '.join(reasons)}]")
    return "\n".join(lines) + "\n"


def main():
    force = "--force-empty" in sys.argv
    roster, claims, comments = load_roster(), load_claims(), load_comments()
    subjects = sorted(set(roster) | set(claims) | set(comments))

    created = skipped = regenerated = 0
    for sid in subjects:
        path = os.path.join(PLACES, sid, "PLACE.yml")
        if os.path.exists(path):
            if not (force and open(path).readline().startswith(MARKER)):
                skipped += 1
                continue
            regenerated += 1
        else:
            created += 1
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as fh:
            fh.write(emit(sid, roster, claims.get(sid, {}), comments))

    tolerated = sum(1 for s in subjects if s in roster)
    print(f"{len(subjects)} addresses: {tolerated} tolerated, {len(subjects) - tolerated} off-roster")
    print(f"created {created}, regenerated {regenerated}, left alone {skipped}")
    print(f"with own coordinates: {sum(1 for s in subjects if own_coordinate(claims.get(s, {})))}")
    print(f"with comment facts:   {len(comments)}")


if __name__ == "__main__":
    main()
